name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Decode google-services.json
        env:
          SECRET: ${{SECRET }}
        run: echo $SECRET > .main/kotlin/Constatnt.kt

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
